### ISSUE TITLE
Deployment to GCP failing (generally concerned about level of DC/OS support)

### ISSUE THREAD

**Issue by Miles-Garnsey** [dcos/dcos-launch#106] opened 2018-03-28 00:59 UTC
Hoping someone can shed some light on this for me. I'm trying to do a demo of DCOS for my team, and I'm having horrible issues with installation on both Digital Ocean as well as GCP.  AWS is usually my weapon of choice but isn't an option here unfortunately.

Steps I've taken from the Google Cloud console;

1. Open a cloud shell session, 
2. wget https://downloads.dcos.io/dcos-launch/bin/linux/dcos-launch
3. Create the config file below.
4. Create a service account with a JSON ssh key against it.
5. export GCE_CREDENTIALS= '<<JSON credentials>>'
4. dcos-launch create && dcos-wait

From the error, it looks like it is looking for the wrong virtual machine names. Suspect that the ones it is looking for are those it created on my previous, which were deleted using dcos-launch delete. 

Happy to acknowledge that my issues likely arise from user error (I'm a total newb on GCP and not that proficient at Mesos configuration), but I'm concerned that the Mesos development team aren't providing as much support as would be desirable to promote their growth. I can't convince my side to pay for commercial support unless we can stand up a demo in a reasonably painless fashion. I keep telling them how easy it is to use - but the technology keeps proving me wrong... 

Can any kind person provide some assistance?

**Config.yaml**
Note that I'm trying to stand up just two nodes on 2 core machines, as I'm using the free trial of GCP for demo purposes.

> ---
> launch_config_version: 1
> deployment_name: dcos-demo
> installer_url: https://downloads.dcos.io/dcos/testing/master/dcos_generate_config.sh
> platform: gce
> provider: onprem
> source_image: coreos-stable-1465-6-0-v20170817
> dcos_config:
>     cluster_name: My Awesome DC/OS
>     resolvers:
>         - 8.8.4.4
>         - 8.8.8.8
>     dns_search: mesos    
>     master_discovery: static
>     exhibitor_storage_backend: zookeeper
>     exhibitor_zk_path: /exhibitor
> num_masters: 1
> num_private_agents: 1
> num_public_agents: 0
> machine_type: n1-standard-2
> use_preemptible_vms: True
> key_helper: true
> gce_zone: us-west1-a
> disable_updates: True

**JSON Credentials**

{
  "type": "service_account",
  "project_id": "mesos-199305",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": ""
}

**Errors**

File "site-packages/googleapiclient/http.py", line 844, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/mesos-199305/zones/us-west1-a/instances/vm-12kj?alt=json returned "The resource 'p
rojects/mesos-199305/zones/us-west1-a/instances/vm-12kj' was not found">
[2018-03-28 10:22:13,127|dcos_launch.platforms.gcp|ERROR]: The resource you are trying to access doesn't exist
Traceback (most recent call last):
  File "dcos_launch/platforms/gcp.py", line 161, in handle_exception
  File "dcos_launch/platforms/gcp.py", line 195, in get_instance_info
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/http.py", line 844, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/mesos-199305/zones/us-west1-a/instances/vm-12kj?alt=json returned "The resource 'p
rojects/mesos-199305/zones/us-west1-a/instances/vm-12kj' was not found">
Traceback (most recent call last):
  File "dcos_launch/cli.py", line 132, in <module>
  File "dcos_launch/cli.py", line 124, in main
  File "dcos_launch/cli.py", line 90, in do_main
  File "dcos_launch/gcp.py", line 95, in wait
  File "dcos_launch/onprem.py", line 180, in wait
  File "dcos_launch/onprem.py", line 27, in get_onprem_cluster
  File "dcos_launch/gcp.py", line 87, in get_bootstrap_host
  File "dcos_launch/platforms/gcp.py", line 454, in hosts
  File "site-packages/retrying.py", line 49, in wrapped_f
  File "site-packages/retrying.py", line 212, in call
  File "site-packages/retrying.py", line 247, in get
  File "site-packages/six.py", line 693, in reraise
  File "site-packages/retrying.py", line 200, in call
  File "dcos_launch/platforms/gcp.py", line 210, in get_instance_network_properties
  File "dcos_launch/platforms/gcp.py", line 168, in handle_exception
  File "dcos_launch/platforms/gcp.py", line 161, in handle_exception
  File "dcos_launch/platforms/gcp.py", line 195, in get_instance_info
  File "site-packages/oauth2client/util.py", line 137, in positional_wrapper
  File "site-packages/googleapiclient/http.py", line 844, in execute
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/compute/v1/projects/mesos-199305/zones/us-west1-a/instances/vm-12kj?alt=json returned "The resource 'p
rojects/mesos-199305/zones/us-west1-a/instances/vm-12kj' was not found">

**Comment by Miles-Garnsey** [comment] 2018-03-28 02:40
Oh, and just as a side note also; the DC/OS site doesn't mention anything about the launcher utility, and instead refers me back to using either Terraform or Ansible (it differs for version 1.11 and 1.10). I couldn't get either of these to work either.

**Comment by cprovencher** [comment] 2018-03-28 18:25
@Miles-Garnsey will take a look. Can you provide details about your issue while using terraform as well?

**Comment by cprovencher** [comment] 2018-03-28 23:21
@Miles-Garnsey 
Potential solution: I could not reproduce your error, but what I suggest is In your config, enter a deployment name that is different from your last deployment's.
I would also recommend using these minimum numbers in your config to make sure DC/OS works properly:
num_masters: 1
num_private_agents: 2
num_public_agents: 1

What I think happened: Either your last deployment did not finish deleting its instance group or failed to do so. So when you're trying to launch a new deployment with the same name, it is still looking for the VM names associated with the old instance group. The new deployment thinks the old instance group is his because it has its name in it e.g. dcos-demo-group.

If that works, GCE on dcos-launch could be fine for your demo, but the recommended, official way of deploying DC/OS on GCE is by using Ansible as you have tried previously (https://docs.mesosphere.com/1.11/installing/oss/cloud/gce/). If you encounter any problems with this deployment method, you can get community support here under "Get Help":
https://dcos.io/community/

There also should be a dcos-launch update by the end of this week that introduces "Terraform on dcos-launch", which should make deploying DC/OS on GCE very easy.

**Comment by Miles-Garnsey** [comment] 2018-04-03 06:59
Hi @cprovencher, thanks for the quick response, apologies that Easter has delayed my own. I've deleted the instance group entirely and also tried changing the name. However, I note a commit associated with this issue may have resolved it. I will test and update you, and will add the Terraform error I received also.

As a side note, I really appreciate the support - not only does it address my worry that Mesosphere might not be as active as would be ideal, it is also a great example for my team of how effective the open source workflow and support model is :+1:

**Comment by Miles-Garnsey** [comment] 2018-04-05 07:09
No luck with the ansible approach on the [DC/OS website](https://docs.mesosphere.com/1.11/installing/oss/cloud/gce/). I raised a ticket [here](https://jira.mesosphere.com/browse/DCOS_OSS-2342)

Error - 

`TASK [remove masters from known_hosts file] ********************************************************************************************************************************************************
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/usr/bin/ssh-keygen", "-R", "master0"], "delta": "0:00:00.009169", "end": "2018-04-05 07:05:11.995404", "item": "master0", "msg": "
non-zero return code", "rc": 255, "start": "2018-04-05 07:05:11.986235", "stderr": "mkstemp: No such file or directory", "stderr_lines": ["mkstemp: No such file or directory"], "stdout": "", "stdo
ut_lines": []}
...ignoring
TASK [remove  masters IP from known_hosts file] ****************************************************************************************************************************************************
failed: [localhost] (item=master0) => {"changed": true, "cmd": ["/usr/bin/ssh-keygen", "-R", "35.189.55.156"], "delta": "0:00:00.008994", "end": "2018-04-05 07:05:12.281870", "item": "master0", "m
sg": "non-zero return code", "rc": 255, "start": "2018-04-05 07:05:12.272876", "stderr": "mkstemp: No such file or directory", "stderr_lines": ["mkstemp: No such file or directory"], "stdout": "",
 "stdout_lines": []}
...ignoring
TASK [Create and launch masters] *******************************************************************************************************************************************************************
changed: [localhost] => (item=master0)
TASK [wait for master instance creation to complete] ***********************************************************************************************************************************************
failed: [localhost] (item={'_ansible_parsed': True, '_ansible_item_result': True, '_ansible_no_log': False, u'ansible_job_id': u'988786078443.2700', 'failed': False, u'started': 1, 'changed': True
, 'item': u'master0', u'finished': 0, u'results_file': u'/root/.ansible_async/988786078443.2700', '_ansible_ignore_errors': None}) => {"ansible_job_id": "988786078443.2700", "attempts": 1, "change
d": true, "cmd": ["/usr/bin/gcloud", "compute", "--project", "mesos", "instances", "create", "master0", "--zone", "australia-southeast1-b", "--machine-type", "n1-standard-2", "--subnet", "default"
, "--private-network-ip", "35.189.55.156", "--maintenance-policy", "MIGRATE", "--tags", "master", "--scopes", "default=https://www.googleapis.com/auth/cloud-platform", "--image", "centos-7-v201610
27", "--image-project", "centos-cloud", "--boot-disk-size", "10", "--boot-disk-type", "pd-standard", "--boot-disk-device-name", "master0-boot", "--metadata", "hostname=master0"], "delta": "0:00:01
.272345", "end": "2018-04-05 07:05:13.897655", "finished": 1, "item": {"ansible_job_id": "988786078443.2700", "changed": true, "failed": false, "finished": 0, "item": "master0", "results_file": "/
root/.ansible_async/988786078443.2700", "started": 1}, "msg": "non-zero return code", "rc": 1, "start": "2018-04-05 07:05:12.625310", "stderr": "WARNING: You have selected a disk size of under [20
0GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.\nERROR: (gcloud.compute.instances.create) Invalid value for 
[--scopes]: Flag format --scopes [ACCOUNT=]SCOPE,[[ACCOUNT=]SCOPE, ...] is removed. Use --scopes [SCOPE,...] --service-account ACCOUNT instead.", "stderr_lines": ["WARNING: You have selected a dis
k size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.", "ERROR: (gcloud.compute.instances.creat
e) Invalid value for [--scopes]: Flag format --scopes [ACCOUNT=]SCOPE,[[ACCOUNT=]SCOPE, ...] is removed. Use --scopes [SCOPE,...] --service-account ACCOUNT instead."], "stdout": "", "stdout_lines"
: []}
        to retry, use: --limit @/home/miles_garnsey/dcos-gce/install.retry
PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=11   changed=7    unreachable=0    failed=1   
`

**Comment by Miles-Garnsey** [comment] 2018-04-05 07:11
Also, looks like that commit that got my hopes up is for Terraform. I can't actually track down those instructions now (someone needs to review the DC/OS website as the structure is a bit mangled). 

If someone can point me in the right direction I'll  gladly test.

**Comment by cprovencher** [comment] 2018-04-06 02:28
Hi @Miles-Garnsey 
I've just merged big changes on dcos-launch and terraform-dcos.
Can you download the latest dcos-launch binary and try deploying with dcos-launch again?
Go through the 6 steps (except dcos-launch with sudo) you listed in your first message and use this config:
```
---
launch_config_version: 1
platform: gcp
provider: terraform
dcos-enterprise: False
terraform_config:
  owner: mgarnsey
  num_of_masters: 1
  num_of_private_agents: 2
  num_of_public_agents: 1
  gcp_bootstrap_instance_type: n1-standard-1
  gcp_master_instance_type: n1-standard-1
  gcp_agent_instance_type: n1-standard-1
  gcp_public_agent_instance_type:  n1-standard-1
```

I just deployed a cluster with no problem using that config and the latest dcos-launch binary. Let me know how that works for you.

**Comment by Miles-Garnsey** [comment] 2018-04-13 04:32
@cprovencher, I think I figured out my error. GCP doesn't give you very many static IPs to use, and I was hitting my quota due to using a free evaluation account. I've tried again and it looks like I can now get both your config above, as well as the (non-terraform) gcp-onprem.yaml to work.

Thanks again for your help, deploying Mesos to GCP with only a few commands is awesome.

**Comment by cprovencher** [comment] 2018-04-15 03:48
@Miles-Garnsey Great I'm glad you could get it to work

**Comment by cprovencher** [comment] 2018-04-15 03:49
@Miles-Garnsey Great I'm glad you could get it to work

**Closed as completed by cprovencher** 2018-04-15 03:49 UTC
